version: '3.3'
services:
  nginx: 
    image: nginx:latest
    container_name: patrick-conroy.local
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 443:443
      - 80:80
networks:
  default:
    name: mono-network
